#!/bin/bash

 # Script For Building Android arm64 Kernel Local
 #
 # Copyright (c) 2021 vcyzteen <vcyzscape@gmail.com>
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #

# main
echo -e "type your defconfig here: "
read -e DEFCONFIG 
echo -e "type your user kbuild here: "
read -e USER
echo -e "type your host kbuild here: "
read -e HOST 
echo -e "type your path folder clang here: "
read -e CLANG
# export user and host
export KBUILD_BUILD_USER=$USER
export KBUILD_BUILD_HOST=$HOST
# start compile
function clang() {
    make -j$(nproc) O=out ARCH=arm64 $DEFCONFIG
    make -j$(nproc) ARCH=arm64 O=out \
			CC=$CLANG/clang \
			AR=$CLANG/llvm-ar \
			NM=$CLANG/llvm-nm \
			OBJCOPY=$CLANG/llvm-objcopy \
			OBJDUMP=$CLANG/llvm-objdump \
			STRIP=$CLANG/llvm-strip \
			CROSS_COMPILE=$CLANG/aarch64-linux-gnu- \
			CROSS_COMPILE_ARM32=$CLANG/arm-linux-gnueabi-
}
clang
