# Run a couple of linters on code in repo
# * shellcheck and shfmt for shell scripts
# * YAPF for Python scripts
name: Lint checks
on: [push, pull_request]
jobs:
  shellcheck:
    uses: Baka-Compile/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: Baka-Compile/actions-workflows/.github/workflows/shfmt.yml@main
